// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: b1utx8z56xvEqoRYjndhny
// Component: J6TP2UqGTBvh

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Button from "../../Button"; // plasmic-import: 1Tp9dwCgkcoM/component

import { useScreenVariants as useScreenVariantszEvd9K3IhaQ } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: zEvd9k3iha-q/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: b1utx8z56xvEqoRYjndhny/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: J6TP2UqGTBvh/css

import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: bpaamlAu2rB6/icon
import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: 2nYlYHhsGp_d/icon
import _227601RightArrowIconSvgIcon from "./icons/PlasmicIcon___227601RightArrowIconSvg"; // plasmic-import: -ine5PlhH6xe/icon

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: Flex__<"div">;
  navBar?: Flex__<"header">;
  logoWrap?: Flex__<"div">;
  logo?: Flex__<typeof PlasmicImg__>;
  navmenu?: Flex__<"div">;
  link3?: Flex__<"a"> & Partial<LinkProps>;
  link2?: Flex__<"a"> & Partial<LinkProps>;
  navBarButtonBlock?: Flex__<"div">;
  button?: Flex__<typeof Button>;
  btnText?: Flex__<"div">;
  section1?: Flex__<"section">;
  container?: Flex__<"div">;
  flexBox?: Flex__<"div">;
  bannerImage?: Flex__<"div">;
  contentBlock?: Flex__<"div">;
  mainHeading?: Flex__<"h1">;
  peraBanner?: Flex__<"p">;
  section2?: Flex__<"section">;
  subHeading?: Flex__<"h2">;
  logoContainer?: Flex__<"div">;
  section3?: Flex__<"section">;
  twoSideBox?: Flex__<"div">;
  subHeading2?: Flex__<"h2">;
  peraContent?: Flex__<"p">;
  unorderList?: Flex__<"ul">;
  listIteam?: Flex__<"li">;
  listIteam3?: Flex__<"li">;
  listIteam4?: Flex__<"li">;
  listIteam5?: Flex__<"li">;
  listIteam6?: Flex__<"li">;
  listIteam7?: Flex__<"li">;
  listIteam8?: Flex__<"li">;
  bannerImage2?: Flex__<"div">;
  imageMarketing2?: Flex__<typeof PlasmicImg__>;
  section4?: Flex__<"section">;
  testimonialText?: Flex__<"h2">;
  position?: Flex__<"p">;
  section5?: Flex__<"section">;
  twoSidedContent?: Flex__<"div">;
  subHeading3?: Flex__<"h2">;
  line2?: Flex__<"div">;
  section6?: Flex__<"section">;
  twoSideBox2?: Flex__<"div">;
  subHeading4?: Flex__<"h2">;
  peraContent2?: Flex__<"p">;
  unorderList2?: Flex__<"ul">;
  listIteam2?: Flex__<"li">;
  listIteam9?: Flex__<"li">;
  listIteam10?: Flex__<"li">;
  listIteam11?: Flex__<"li">;
  listIteam12?: Flex__<"li">;
  listIteam13?: Flex__<"li">;
  bannerImage3?: Flex__<"div">;
  imageMarketing3?: Flex__<typeof PlasmicImg__>;
  section7?: Flex__<"section">;
  subHeading5?: Flex__<"h2">;
  line3?: Flex__<"div">;
  blockChapterContent?: Flex__<"div">;
  blockChapterContent4?: Flex__<"div">;
  blockChapterContent2?: Flex__<"div">;
  blockChapterContent3?: Flex__<"div">;
  section8?: Flex__<"section">;
  avtarContent?: Flex__<"div">;
  avatarImage?: Flex__<"div">;
  section9?: Flex__<"section">;
  svg?: Flex__<"svg">;
  footer?: Flex__<"footer">;
  footerLogo?: Flex__<"div">;
  logo2?: Flex__<typeof PlasmicImg__>;
  footerLink?: Flex__<"a"> & Partial<LinkProps>;
  footerLink2?: Flex__<"a"> & Partial<LinkProps>;
  footerLink4?: Flex__<"a"> & Partial<LinkProps>;
  footerLink5?: Flex__<"a"> & Partial<LinkProps>;
  copyRight?: Flex__<"p">;
  socialIcons?: Flex__<"div">;
  twitter?: Flex__<typeof PlasmicImg__>;
  facebook?: Flex__<typeof PlasmicImg__>;
  youtube?: Flex__<typeof PlasmicImg__>;
  vimeo?: Flex__<typeof PlasmicImg__>;
};

export interface DefaultHomepageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantszEvd9K3IhaQ()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <Stack__
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <header
            data-plasmic-name={"navBar"}
            data-plasmic-override={overrides.navBar}
            className={classNames(projectcss.all, sty.navBar)}
          >
            <div
              data-plasmic-name={"logoWrap"}
              data-plasmic-override={overrides.logoWrap}
              className={classNames(projectcss.all, sty.logoWrap)}
            >
              <PlasmicImg__
                data-plasmic-name={"logo"}
                data-plasmic-override={overrides.logo}
                alt={""}
                className={classNames(sty.logo)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"220px"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/online_course_or_book/images/image8.png",
                  fullWidth: 186,
                  fullHeight: 80,
                  aspectRatio: undefined
                }}
              />
            </div>
            <div
              data-plasmic-name={"navmenu"}
              data-plasmic-override={overrides.navmenu}
              className={classNames(projectcss.all, sty.navmenu)}
            >
              <PlasmicLink__
                data-plasmic-name={"link3"}
                data-plasmic-override={overrides.link3}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link3
                )}
                component={Link}
                href={`/`}
                platform={"nextjs"}
              >
                {"Pricing"}
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"link2"}
                data-plasmic-override={overrides.link2}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link2
                )}
                component={Link}
                href={"#"}
                platform={"nextjs"}
              >
                {"Story"}
              </PlasmicLink__>
            </div>
            <div
              data-plasmic-name={"navBarButtonBlock"}
              data-plasmic-override={overrides.navBarButtonBlock}
              className={classNames(projectcss.all, sty.navBarButtonBlock)}
            >
              <Button
                data-plasmic-name={"button"}
                data-plasmic-override={overrides.button}
                className={classNames("__wab_instance", sty.button)}
                color={"red"}
                shape={"rounded"}
                submitsForm={true}
              >
                <div
                  data-plasmic-name={"btnText"}
                  data-plasmic-override={overrides.btnText}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.btnText
                  )}
                >
                  {"Start Learning"}
                </div>
              </Button>
            </div>
          </header>
          <section
            data-plasmic-name={"section1"}
            data-plasmic-override={overrides.section1}
            className={classNames(projectcss.all, sty.section1)}
          >
            <div
              data-plasmic-name={"container"}
              data-plasmic-override={overrides.container}
              className={classNames(projectcss.all, sty.container)}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"flexBox"}
                data-plasmic-override={overrides.flexBox}
                hasGap={true}
                className={classNames(projectcss.all, sty.flexBox)}
              >
                <div className={classNames(projectcss.all, sty.column__c44Yr)}>
                  <div
                    data-plasmic-name={"bannerImage"}
                    data-plasmic-override={overrides.bannerImage}
                    className={classNames(projectcss.all, sty.bannerImage)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__yqZLi)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/online_course_or_book/images/image2.png",
                        fullWidth: 1332,
                        fullHeight: 2080,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column___0Oa54)}>
                  <div
                    data-plasmic-name={"contentBlock"}
                    data-plasmic-override={overrides.contentBlock}
                    className={classNames(projectcss.all, sty.contentBlock)}
                  >
                    <h1
                      data-plasmic-name={"mainHeading"}
                      data-plasmic-override={overrides.mainHeading}
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.mainHeading
                      )}
                    >
                      {"The Ultimate Guide to High-Performance Landing Pages"}
                    </h1>
                    <p
                      data-plasmic-name={"peraBanner"}
                      data-plasmic-override={overrides.peraBanner}
                      className={classNames(
                        projectcss.all,
                        projectcss.p,
                        sty.peraBanner
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__jIfYl
                        )}
                      >
                        {
                          "Your go-to guide for both B2B and B2C digital marketing pages.\n\nWe will share with you the hard-won tips and tricks we've gained from developing over 75 high-converting landing pages clients across multiple industries. Everything from ad image and copy, to page design and conversion strategies are shared here in broad strokes for you to take home and deploy."
                        }
                      </div>
                    </p>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__ymUz9)}
                    >
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__oRPp0
                        )}
                        color={"red"}
                        shape={"rounded"}
                        showEndIcon={true}
                        submitsForm={true}
                      >
                        {"Access the course"}
                      </Button>
                    </div>
                  </div>
                </div>
              </Stack__>
            </div>
          </section>
          <Stack__
            as={"section"}
            data-plasmic-name={"section2"}
            data-plasmic-override={overrides.section2}
            hasGap={true}
            className={classNames(projectcss.all, sty.section2)}
          >
            <h2
              data-plasmic-name={"subHeading"}
              data-plasmic-override={overrides.subHeading}
              className={classNames(
                projectcss.all,
                projectcss.h2,
                projectcss.__wab_text,
                sty.subHeading
              )}
            >
              {"Used by marketers at:"}
            </h2>
            <Stack__
              as={"div"}
              data-plasmic-name={"logoContainer"}
              data-plasmic-override={overrides.logoContainer}
              hasGap={true}
              className={classNames(projectcss.all, sty.logoContainer)}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__x7CdU)}
                displayHeight={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "auto"
                    : "77px"
                }
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "100px"
                    : "180px"
                }
                loading={"lazy"}
                src={{
                  src: "/plasmic/online_course_or_book/images/group3.svg",
                  fullWidth: 180,
                  fullHeight: 77,
                  aspectRatio: 2.337662
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__gl0Js)}
                displayHeight={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "auto"
                    : "85px"
                }
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "100px"
                    : "180px"
                }
                loading={"lazy"}
                src={{
                  src: "/plasmic/online_course_or_book/images/group6.svg",
                  fullWidth: 180,
                  fullHeight: 85,
                  aspectRatio: 2.117647
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__v8CeK)}
                displayHeight={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "auto"
                    : "66px"
                }
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "120px"
                    : "157px"
                }
                loading={"lazy"}
                src={{
                  src: "/plasmic/online_course_or_book/images/group.svg",
                  fullWidth: 157,
                  fullHeight: 66,
                  aspectRatio: 2.378788
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__n71Fq)}
                displayHeight={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "auto"
                    : "80.999px"
                }
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "100px"
                    : "164.999px"
                }
                loading={"lazy"}
                src={{
                  src: "/plasmic/online_course_or_book/images/group5.svg",
                  fullWidth: 164.999,
                  fullHeight: 80.999,
                  aspectRatio: 2.037037
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__t0Vo)}
                displayHeight={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "auto"
                    : "auto"
                }
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "100px"
                    : "143px"
                }
                loading={"lazy"}
                src={{
                  src: "/plasmic/online_course_or_book/images/group7.svg",
                  fullWidth: 143,
                  fullHeight: 91,
                  aspectRatio: 1.571429
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__iZgg4)}
                displayHeight={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "auto"
                    : "76.999px"
                }
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "138px"
                    : "168.999px"
                }
                loading={"lazy"}
                src={{
                  src: "/plasmic/online_course_or_book/images/group2.svg",
                  fullWidth: 168.999,
                  fullHeight: 76.999,
                  aspectRatio: 2.194805
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__nmG9M)}
                displayHeight={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "auto"
                    : "87px"
                }
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "100px"
                    : "152.999px"
                }
                loading={"lazy"}
                src={{
                  src: "/plasmic/online_course_or_book/images/group4.svg",
                  fullWidth: 152.999,
                  fullHeight: 87,
                  aspectRatio: 1.758621
                }}
              />
            </Stack__>
          </Stack__>
          <section
            data-plasmic-name={"section3"}
            data-plasmic-override={overrides.section3}
            className={classNames(projectcss.all, sty.section3)}
          >
            <div
              data-plasmic-name={"twoSideBox"}
              data-plasmic-override={overrides.twoSideBox}
              className={classNames(projectcss.all, sty.twoSideBox)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__t9NaP)}>
                <div className={classNames(projectcss.all, sty.freeBox__ltrM)}>
                  <div
                    className={classNames(projectcss.all, sty.columns__aUsOc)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__fsPsu)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__xdlIu
                        )}
                      >
                        <h2
                          data-plasmic-name={"subHeading2"}
                          data-plasmic-override={overrides.subHeading2}
                          className={classNames(
                            projectcss.all,
                            projectcss.h2,
                            sty.subHeading2
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__my3KV
                            )}
                          >
                            {"What you'll learn"}
                          </div>
                          <p
                            data-plasmic-name={"peraContent"}
                            data-plasmic-override={overrides.peraContent}
                            className={classNames(
                              projectcss.all,
                              projectcss.p,
                              projectcss.__wab_text,
                              sty.peraContent
                            )}
                          >
                            {"How this course will take you from zero to hero:"}
                          </p>
                          <ul
                            data-plasmic-name={"unorderList"}
                            data-plasmic-override={overrides.unorderList}
                            className={classNames(
                              projectcss.all,
                              projectcss.ul,
                              sty.unorderList
                            )}
                          >
                            <li
                              data-plasmic-name={"listIteam"}
                              data-plasmic-override={overrides.listIteam}
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.listIteam
                              )}
                            >
                              {
                                "Describe some topic covered in this info product."
                              }
                            </li>
                            <li
                              data-plasmic-name={"listIteam3"}
                              data-plasmic-override={overrides.listIteam3}
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.listIteam3
                              )}
                            >
                              {
                                "Describe some topic covered in this info product."
                              }
                            </li>
                            <li
                              data-plasmic-name={"listIteam4"}
                              data-plasmic-override={overrides.listIteam4}
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.listIteam4
                              )}
                            >
                              {
                                "Describe some topic covered in this info product."
                              }
                            </li>
                            <li
                              data-plasmic-name={"listIteam5"}
                              data-plasmic-override={overrides.listIteam5}
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.listIteam5
                              )}
                            >
                              {
                                "Describe some topic covered in this info product."
                              }
                            </li>
                            <li
                              data-plasmic-name={"listIteam6"}
                              data-plasmic-override={overrides.listIteam6}
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.listIteam6
                              )}
                            >
                              {
                                "Describe some topic covered in this info product."
                              }
                            </li>
                            <li
                              data-plasmic-name={"listIteam7"}
                              data-plasmic-override={overrides.listIteam7}
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.listIteam7
                              )}
                            >
                              {
                                "Describe some topic covered in this info product."
                              }
                            </li>
                            <li
                              data-plasmic-name={"listIteam8"}
                              data-plasmic-override={overrides.listIteam8}
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.listIteam8
                              )}
                            >
                              {
                                "Describe some topic covered in this info product."
                              }
                            </li>
                          </ul>
                        </h2>
                      </div>
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__smQ3C
                        )}
                        color={"red"}
                        shape={"rounded"}
                        showEndIcon={true}
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__onJm
                          )}
                        >
                          {"Start learning"}
                        </div>
                      </Button>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column___4DuoO)}
                    >
                      <div
                        data-plasmic-name={"bannerImage2"}
                        data-plasmic-override={overrides.bannerImage2}
                        className={classNames(projectcss.all, sty.bannerImage2)}
                      >
                        <PlasmicImg__
                          data-plasmic-name={"imageMarketing2"}
                          data-plasmic-override={overrides.imageMarketing2}
                          alt={""}
                          className={classNames(sty.imageMarketing2)}
                          displayHeight={
                            hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "auto"
                              : "100%"
                          }
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={
                            hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "400px"
                              : "100%"
                          }
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/online_course_or_book/images/image.png",
                            fullWidth: 1600,
                            fullHeight: 1200,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
          <section
            data-plasmic-name={"section4"}
            data-plasmic-override={overrides.section4}
            className={classNames(projectcss.all, sty.section4)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__y5Exs)}>
              <div className={classNames(projectcss.all, sty.columns__r8Rxr)}>
                <div className={classNames(projectcss.all, sty.column__xOry)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__jk1Jc)}
                    displayHeight={"256px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"256px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/online_course_or_book/images/image7.png",
                      fullWidth: 1112,
                      fullHeight: 794,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__i9CfX)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__aePgN)}
                  >
                    <h2
                      data-plasmic-name={"testimonialText"}
                      data-plasmic-override={overrides.testimonialText}
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.testimonialText
                      )}
                    >
                      {
                        "\u201cThis course is a must-take for anyone in digital marketing. Worth every penny.\u201d"
                      }
                    </h2>
                    <p
                      data-plasmic-name={"position"}
                      data-plasmic-override={overrides.position}
                      className={classNames(
                        projectcss.all,
                        projectcss.p,
                        projectcss.__wab_text,
                        sty.position
                      )}
                    >
                      {"Jane Doe, Sr. Marketing Manager at Company"}
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </section>
          <section
            data-plasmic-name={"section5"}
            data-plasmic-override={overrides.section5}
            className={classNames(projectcss.all, sty.section5)}
          >
            <div
              data-plasmic-name={"twoSidedContent"}
              data-plasmic-override={overrides.twoSidedContent}
              className={classNames(projectcss.all, sty.twoSidedContent)}
            >
              <h2
                data-plasmic-name={"subHeading3"}
                data-plasmic-override={overrides.subHeading3}
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.subHeading3
                )}
              >
                {"Curriculum Overview"}
              </h2>
              <div
                data-plasmic-name={"line2"}
                data-plasmic-override={overrides.line2}
                className={classNames(projectcss.all, sty.line2)}
              />

              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__bp1BI)}
              >
                <div className={classNames(projectcss.all, sty.column__qXxDr)}>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__yt50O
                    )}
                  >
                    {"Chapter Title"}
                  </h2>
                  <p
                    className={classNames(
                      projectcss.all,
                      projectcss.p,
                      projectcss.__wab_text,
                      sty.p__jpucu
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                    }
                  </p>
                </div>
                <div className={classNames(projectcss.all, sty.column__gHMbe)}>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__ydcmC
                    )}
                  >
                    {"Chapter Title"}
                  </h2>
                  <p
                    className={classNames(
                      projectcss.all,
                      projectcss.p,
                      projectcss.__wab_text,
                      sty.p__yFsaj
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                    }
                  </p>
                </div>
                <div className={classNames(projectcss.all, sty.column__acYn7)}>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__gljRn
                    )}
                  >
                    {"Chapter Title"}
                  </h2>
                  <p
                    className={classNames(
                      projectcss.all,
                      projectcss.p,
                      projectcss.__wab_text,
                      sty.p__hbJyz
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                    }
                  </p>
                </div>
                <div className={classNames(projectcss.all, sty.column__uit5T)}>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__zt6Lg
                    )}
                  >
                    {"Chapter Title"}
                  </h2>
                  <p
                    className={classNames(
                      projectcss.all,
                      projectcss.p,
                      projectcss.__wab_text,
                      sty.p__cqFuz
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                    }
                  </p>
                </div>
                <div className={classNames(projectcss.all, sty.column__tOqe)}>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__klP8
                    )}
                  >
                    {"Chapter Title"}
                  </h2>
                  <p
                    className={classNames(
                      projectcss.all,
                      projectcss.p,
                      projectcss.__wab_text,
                      sty.p__tVjfq
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                    }
                  </p>
                </div>
                <div className={classNames(projectcss.all, sty.column__wexB6)}>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__dt1LD
                    )}
                  >
                    {"Chapter Title"}
                  </h2>
                  <p
                    className={classNames(
                      projectcss.all,
                      projectcss.p,
                      projectcss.__wab_text,
                      sty.p___3TFe8
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                    }
                  </p>
                </div>
              </Stack__>
            </div>
          </section>
          <section
            data-plasmic-name={"section6"}
            data-plasmic-override={overrides.section6}
            className={classNames(projectcss.all, sty.section6)}
          >
            <div
              data-plasmic-name={"twoSideBox2"}
              data-plasmic-override={overrides.twoSideBox2}
              className={classNames(projectcss.all, sty.twoSideBox2)}
            >
              <div className={classNames(projectcss.all, sty.columns__h7Lay)}>
                <div className={classNames(projectcss.all, sty.column___84To)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__oxBza)}
                  >
                    <h2
                      data-plasmic-name={"subHeading4"}
                      data-plasmic-override={overrides.subHeading4}
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        sty.subHeading4
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ltBvs
                        )}
                      >
                        {"Practical exercises"}
                      </div>
                      <p
                        data-plasmic-name={"peraContent2"}
                        data-plasmic-override={overrides.peraContent2}
                        className={classNames(
                          projectcss.all,
                          projectcss.p,
                          projectcss.__wab_text,
                          sty.peraContent2
                        )}
                      >
                        {"How you'll implement what you learn"}
                      </p>
                      <ul
                        data-plasmic-name={"unorderList2"}
                        data-plasmic-override={overrides.unorderList2}
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.unorderList2
                        )}
                      >
                        <li
                          data-plasmic-name={"listIteam2"}
                          data-plasmic-override={overrides.listIteam2}
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.listIteam2
                          )}
                        >
                          {"Describe a practice exercise."}
                        </li>
                        <li
                          data-plasmic-name={"listIteam9"}
                          data-plasmic-override={overrides.listIteam9}
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.listIteam9
                          )}
                        >
                          {"Describe a practice exercise."}
                        </li>
                        <li
                          data-plasmic-name={"listIteam10"}
                          data-plasmic-override={overrides.listIteam10}
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.listIteam10
                          )}
                        >
                          {"Describe a practice exercise."}
                        </li>
                        <li
                          data-plasmic-name={"listIteam11"}
                          data-plasmic-override={overrides.listIteam11}
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.listIteam11
                          )}
                        >
                          {"Describe a practice exercise."}
                        </li>
                        <li
                          data-plasmic-name={"listIteam12"}
                          data-plasmic-override={overrides.listIteam12}
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.listIteam12
                          )}
                        >
                          {"Describe a practice exercise."}
                        </li>
                        <li
                          data-plasmic-name={"listIteam13"}
                          data-plasmic-override={overrides.listIteam13}
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.listIteam13
                          )}
                        >
                          {"Describe a practice exercise."}
                        </li>
                      </ul>
                    </h2>
                  </div>
                  <Button
                    className={classNames("__wab_instance", sty.button___8DAjN)}
                    color={"red"}
                    shape={"rounded"}
                    showEndIcon={true}
                    submitsForm={true}
                  >
                    {"Start learning"}
                  </Button>
                </div>
                <div className={classNames(projectcss.all, sty.column__mSf0L)}>
                  <div
                    data-plasmic-name={"bannerImage3"}
                    data-plasmic-override={overrides.bannerImage3}
                    className={classNames(projectcss.all, sty.bannerImage3)}
                  >
                    <PlasmicImg__
                      data-plasmic-name={"imageMarketing3"}
                      data-plasmic-override={overrides.imageMarketing3}
                      alt={""}
                      className={classNames(sty.imageMarketing3)}
                      displayHeight={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "auto"
                          : "100%"
                      }
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "400px"
                          : "100%"
                      }
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/online_course_or_book/images/image.png",
                        fullWidth: 1600,
                        fullHeight: 1200,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                </div>
              </div>
            </div>
          </section>
          <section
            data-plasmic-name={"section7"}
            data-plasmic-override={overrides.section7}
            className={classNames(projectcss.all, sty.section7)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__mNlkv)}>
              <h2
                data-plasmic-name={"subHeading5"}
                data-plasmic-override={overrides.subHeading5}
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.subHeading5
                )}
              >
                {"Who should take this course?"}
              </h2>
              <div
                data-plasmic-name={"line3"}
                data-plasmic-override={overrides.line3}
                className={classNames(projectcss.all, sty.line3)}
              />
            </div>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__iCxd)}
            >
              <div className={classNames(projectcss.all, sty.column__gKaGp)}>
                <div
                  data-plasmic-name={"blockChapterContent"}
                  data-plasmic-override={overrides.blockChapterContent}
                  className={classNames(
                    projectcss.all,
                    sty.blockChapterContent
                  )}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__isyxV
                    )}
                  >
                    {"Marketers"}
                  </div>
                  <li
                    className={classNames(
                      projectcss.all,
                      projectcss.li,
                      projectcss.__wab_text,
                      sty.li__jXPkA
                    )}
                  >
                    {"Learn how all of the marketing pieces fit together"}
                  </li>
                  <li
                    className={classNames(
                      projectcss.all,
                      projectcss.li,
                      projectcss.__wab_text,
                      sty.li__poR5C
                    )}
                  >
                    {"Master digital marketing for any business"}
                  </li>
                  <li
                    className={classNames(
                      projectcss.all,
                      projectcss.li,
                      projectcss.__wab_text,
                      sty.li__xnpu9
                    )}
                  >
                    {"Get access to marketing gurus and their tips"}
                  </li>
                  <li
                    className={classNames(
                      projectcss.all,
                      projectcss.li,
                      projectcss.__wab_text,
                      sty.li__nh0Z4
                    )}
                  >
                    {"Prepare killer presentations and collateral"}
                  </li>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__du4Gq)}>
                <div
                  data-plasmic-name={"blockChapterContent4"}
                  data-plasmic-override={overrides.blockChapterContent4}
                  className={classNames(
                    projectcss.all,
                    sty.blockChapterContent4
                  )}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__nqEzi
                    )}
                  >
                    {"Product managers"}
                  </div>
                  <li
                    className={classNames(
                      projectcss.all,
                      projectcss.li,
                      projectcss.__wab_text,
                      sty.li__mt8Ya
                    )}
                  >
                    {"Understand the context of your product work"}
                  </li>
                  <li
                    className={classNames(
                      projectcss.all,
                      projectcss.li,
                      projectcss.__wab_text,
                      sty.li__wZlj
                    )}
                  >
                    {"Learn how to segment your audience properly"}
                  </li>
                  <li
                    className={classNames(
                      projectcss.all,
                      projectcss.li,
                      projectcss.__wab_text,
                      sty.li__s7H3
                    )}
                  >
                    {"Implement brand voice and style in your work"}
                  </li>
                  <li
                    className={classNames(
                      projectcss.all,
                      projectcss.li,
                      projectcss.__wab_text,
                      sty.li__mw3R
                    )}
                  >
                    {"Connect top of funnel activities with your flow"}
                  </li>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__ckyxT)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___2QKiL
                  )}
                >
                  {"Designers"}
                </div>
                <li
                  className={classNames(
                    projectcss.all,
                    projectcss.li,
                    sty.li__ujH83
                  )}
                >
                  <li
                    className={classNames(
                      projectcss.all,
                      projectcss.li,
                      projectcss.__wab_text,
                      sty.li__rcMBk
                    )}
                  >
                    {"Learn how your design can inspire action"}
                  </li>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__llyju
                    )}
                  >
                    {"Gain big picture insights that affect design"}
                  </div>
                  <div
                    data-plasmic-name={"blockChapterContent2"}
                    data-plasmic-override={overrides.blockChapterContent2}
                    className={classNames(
                      projectcss.all,
                      sty.blockChapterContent2
                    )}
                  >
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        projectcss.__wab_text,
                        sty.li__zUtVq
                      )}
                    >
                      {"Make advertisements that convert"}
                    </li>
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        projectcss.__wab_text,
                        sty.li__kYvkp
                      )}
                    >
                      {"Create digital assets for the right audience"}
                    </li>
                  </div>
                </li>
              </div>
              <div className={classNames(projectcss.all, sty.column__e8DHn)}>
                <div
                  data-plasmic-name={"blockChapterContent3"}
                  data-plasmic-override={overrides.blockChapterContent3}
                  className={classNames(
                    projectcss.all,
                    sty.blockChapterContent3
                  )}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xW52N
                    )}
                  >
                    {"Business owners"}
                  </div>
                  <li
                    className={classNames(
                      projectcss.all,
                      projectcss.li,
                      projectcss.__wab_text,
                      sty.li__cRiZe
                    )}
                  >
                    {"Kickstart your marketing plan and efforts"}
                  </li>
                  <li
                    className={classNames(
                      projectcss.all,
                      projectcss.li,
                      projectcss.__wab_text,
                      sty.li__kEf0S
                    )}
                  >
                    {"Upgrade your brand, website and social media"}
                  </li>
                  <li
                    className={classNames(
                      projectcss.all,
                      projectcss.li,
                      projectcss.__wab_text,
                      sty.li__aNwBz
                    )}
                  >
                    {"Prepare effective collateral for your business"}
                  </li>
                  <li
                    className={classNames(
                      projectcss.all,
                      projectcss.li,
                      projectcss.__wab_text,
                      sty.li__fOuSv
                    )}
                  >
                    {"Start advertising your company online"}
                  </li>
                </div>
              </div>
            </Stack__>
          </section>
          <section
            data-plasmic-name={"section8"}
            data-plasmic-override={overrides.section8}
            className={classNames(projectcss.all, sty.section8)}
          >
            <div className={classNames(projectcss.all, sty.columns__e0VjT)}>
              <div className={classNames(projectcss.all, sty.column__ymzgk)}>
                <div
                  data-plasmic-name={"avtarContent"}
                  data-plasmic-override={overrides.avtarContent}
                  className={classNames(projectcss.all, sty.avtarContent)}
                >
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__d7Rfl
                    )}
                  >
                    {"About the instructor"}
                  </h2>
                  <p
                    className={classNames(
                      projectcss.all,
                      projectcss.p,
                      projectcss.__wab_text,
                      sty.p___1R1NV
                    )}
                  >
                    {"Jane Doe, Title"}
                  </p>
                  <p
                    className={classNames(
                      projectcss.all,
                      projectcss.p,
                      projectcss.__wab_text,
                      sty.p___59Xe0
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                    }
                  </p>
                  <p
                    className={classNames(
                      projectcss.all,
                      projectcss.p,
                      projectcss.__wab_text,
                      sty.p__qwqzv
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                    }
                  </p>
                  <p
                    className={classNames(
                      projectcss.all,
                      projectcss.p,
                      projectcss.__wab_text,
                      sty.p__e7S8X
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                    }
                  </p>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__kfWmN)}>
                <div
                  data-plasmic-name={"avatarImage"}
                  data-plasmic-override={overrides.avatarImage}
                  className={classNames(projectcss.all, sty.avatarImage)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___43Eat)}
                    displayHeight={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "100%"
                        : "auto"
                    }
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "400px"
                        : "auto"
                    }
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/online_course_or_book/images/image4.png",
                      fullWidth: 930,
                      fullHeight: 1162,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </div>
            </div>
          </section>
          <section
            data-plasmic-name={"section9"}
            data-plasmic-override={overrides.section9}
            className={classNames(projectcss.all, sty.section9)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__uf12W)}>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__j5WSd
                )}
              >
                {"Access the course today"}
              </h2>
            </div>
            <Button
              className={classNames("__wab_instance", sty.button__cwZp)}
              color={"white"}
              endIcon={
                <_227601RightArrowIconSvgIcon
                  data-plasmic-name={"svg"}
                  data-plasmic-override={overrides.svg}
                  className={classNames(projectcss.all, sty.svg)}
                  role={"img"}
                />
              }
              shape={"rounded"}
              submitsForm={true}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___3Y8Bx
                )}
              >
                {"Access the course"}
              </div>
            </Button>
          </section>
          <footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames(projectcss.all, sty.footer)}
          >
            <div className={classNames(projectcss.all, sty.columns__xfgeX)}>
              <div className={classNames(projectcss.all, sty.column__v7HtI)}>
                <div
                  data-plasmic-name={"footerLogo"}
                  data-plasmic-override={overrides.footerLogo}
                  className={classNames(projectcss.all, sty.footerLogo)}
                >
                  <PlasmicImg__
                    data-plasmic-name={"logo2"}
                    data-plasmic-override={overrides.logo2}
                    alt={""}
                    className={classNames(sty.logo2)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"300px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/online_course_or_book/images/image9.png",
                      fullWidth: 374,
                      fullHeight: 156,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__hOmn0)}>
                <h3
                  className={classNames(
                    projectcss.all,
                    projectcss.h3,
                    projectcss.__wab_text,
                    sty.h3__rPq87
                  )}
                >
                  {"Company"}
                </h3>
                <PlasmicLink__
                  data-plasmic-name={"footerLink"}
                  data-plasmic-override={overrides.footerLink}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.footerLink
                  )}
                  component={Link}
                  href={`/`}
                  platform={"nextjs"}
                >
                  {"Story"}
                </PlasmicLink__>
                <PlasmicLink__
                  data-plasmic-name={"footerLink2"}
                  data-plasmic-override={overrides.footerLink2}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.footerLink2
                  )}
                  component={Link}
                  href={`/`}
                  platform={"nextjs"}
                >
                  {"Pricing"}
                </PlasmicLink__>
              </div>
              <div className={classNames(projectcss.all, sty.column__mUpvM)}>
                <h3
                  className={classNames(
                    projectcss.all,
                    projectcss.h3,
                    projectcss.__wab_text,
                    sty.h3__txEt2
                  )}
                >
                  {"Legal"}
                </h3>
                <PlasmicLink__
                  data-plasmic-name={"footerLink4"}
                  data-plasmic-override={overrides.footerLink4}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.footerLink4
                  )}
                  component={Link}
                  href={`/`}
                  platform={"nextjs"}
                >
                  {"Terms & Conditions"}
                </PlasmicLink__>
                <PlasmicLink__
                  data-plasmic-name={"footerLink5"}
                  data-plasmic-override={overrides.footerLink5}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.footerLink5
                  )}
                  component={Link}
                  href={`/`}
                  platform={"nextjs"}
                >
                  {"Privacy Policy"}
                </PlasmicLink__>
              </div>
            </div>
          </footer>
          <div className={classNames(projectcss.all, sty.freeBox__soHIh)}>
            <div className={classNames(projectcss.all, sty.columns__qUYpd)}>
              <div className={classNames(projectcss.all, sty.column__yjPLo)}>
                <p
                  data-plasmic-name={"copyRight"}
                  data-plasmic-override={overrides.copyRight}
                  className={classNames(
                    projectcss.all,
                    projectcss.p,
                    projectcss.__wab_text,
                    sty.copyRight
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>
                      {
                        "\u00a9 Company. All rights reserved. This site proudly built with "
                      }
                    </React.Fragment>
                    {
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link__zoAyQ
                        )}
                        component={Link}
                        href={"https://www.plasmic.app"}
                        platform={"nextjs"}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "Plasmic"
                          : "Plasmic"}
                      </PlasmicLink__>
                    }
                    <React.Fragment>{"."}</React.Fragment>
                  </React.Fragment>
                </p>
              </div>
              <div className={classNames(projectcss.all, sty.column__qny7)}>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"socialIcons"}
                  data-plasmic-override={overrides.socialIcons}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.socialIcons)}
                >
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__qcPte
                    )}
                    component={Link}
                    href={"https://twitter.com/"}
                    platform={"nextjs"}
                    target={"_blank"}
                  >
                    <PlasmicImg__
                      data-plasmic-name={"twitter"}
                      data-plasmic-override={overrides.twitter}
                      alt={""}
                      className={classNames(sty.twitter)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"30px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/online_course_or_book/images/icons8TwitterSvg.svg",
                        fullWidth: 150,
                        fullHeight: 150,
                        aspectRatio: 1
                      }}
                    />
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__dfONp
                    )}
                    component={Link}
                    href={"#"}
                    platform={"nextjs"}
                    target={"_blank"}
                  >
                    <PlasmicImg__
                      data-plasmic-name={"facebook"}
                      data-plasmic-override={overrides.facebook}
                      alt={""}
                      className={classNames(sty.facebook)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"30px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/online_course_or_book/images/icons8FacebookSvg.svg",
                        fullWidth: 150,
                        fullHeight: 150,
                        aspectRatio: 1
                      }}
                    />
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__axknI
                    )}
                    component={Link}
                    href={"#"}
                    platform={"nextjs"}
                    target={"_blank"}
                  >
                    <PlasmicImg__
                      data-plasmic-name={"youtube"}
                      data-plasmic-override={overrides.youtube}
                      alt={""}
                      className={classNames(sty.youtube)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"30px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/online_course_or_book/images/icons8YoutubeSvg.svg",
                        fullWidth: 150,
                        fullHeight: 150,
                        aspectRatio: 1
                      }}
                    />
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link___7QqcT
                    )}
                    component={Link}
                    href={"#"}
                    platform={"nextjs"}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__mUv7Q)}
                    >
                      <PlasmicImg__
                        data-plasmic-name={"vimeo"}
                        data-plasmic-override={overrides.vimeo}
                        alt={""}
                        className={classNames(sty.vimeo)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"30px"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/online_course_or_book/images/icons8VimeoSvg.svg",
                          fullWidth: 150,
                          fullHeight: 150,
                          aspectRatio: 1
                        }}
                      />
                    </div>
                  </PlasmicLink__>
                </Stack__>
              </div>
            </div>
          </div>
        </Stack__>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "navBar",
    "logoWrap",
    "logo",
    "navmenu",
    "link3",
    "link2",
    "navBarButtonBlock",
    "button",
    "btnText",
    "section1",
    "container",
    "flexBox",
    "bannerImage",
    "contentBlock",
    "mainHeading",
    "peraBanner",
    "section2",
    "subHeading",
    "logoContainer",
    "section3",
    "twoSideBox",
    "subHeading2",
    "peraContent",
    "unorderList",
    "listIteam",
    "listIteam3",
    "listIteam4",
    "listIteam5",
    "listIteam6",
    "listIteam7",
    "listIteam8",
    "bannerImage2",
    "imageMarketing2",
    "section4",
    "testimonialText",
    "position",
    "section5",
    "twoSidedContent",
    "subHeading3",
    "line2",
    "section6",
    "twoSideBox2",
    "subHeading4",
    "peraContent2",
    "unorderList2",
    "listIteam2",
    "listIteam9",
    "listIteam10",
    "listIteam11",
    "listIteam12",
    "listIteam13",
    "bannerImage3",
    "imageMarketing3",
    "section7",
    "subHeading5",
    "line3",
    "blockChapterContent",
    "blockChapterContent4",
    "blockChapterContent2",
    "blockChapterContent3",
    "section8",
    "avtarContent",
    "avatarImage",
    "section9",
    "svg",
    "footer",
    "footerLogo",
    "logo2",
    "footerLink",
    "footerLink2",
    "footerLink4",
    "footerLink5",
    "copyRight",
    "socialIcons",
    "twitter",
    "facebook",
    "youtube",
    "vimeo"
  ],
  navBar: [
    "navBar",
    "logoWrap",
    "logo",
    "navmenu",
    "link3",
    "link2",
    "navBarButtonBlock",
    "button",
    "btnText"
  ],
  logoWrap: ["logoWrap", "logo"],
  logo: ["logo"],
  navmenu: ["navmenu", "link3", "link2"],
  link3: ["link3"],
  link2: ["link2"],
  navBarButtonBlock: ["navBarButtonBlock", "button", "btnText"],
  button: ["button", "btnText"],
  btnText: ["btnText"],
  section1: [
    "section1",
    "container",
    "flexBox",
    "bannerImage",
    "contentBlock",
    "mainHeading",
    "peraBanner"
  ],
  container: [
    "container",
    "flexBox",
    "bannerImage",
    "contentBlock",
    "mainHeading",
    "peraBanner"
  ],
  flexBox: [
    "flexBox",
    "bannerImage",
    "contentBlock",
    "mainHeading",
    "peraBanner"
  ],
  bannerImage: ["bannerImage"],
  contentBlock: ["contentBlock", "mainHeading", "peraBanner"],
  mainHeading: ["mainHeading"],
  peraBanner: ["peraBanner"],
  section2: ["section2", "subHeading", "logoContainer"],
  subHeading: ["subHeading"],
  logoContainer: ["logoContainer"],
  section3: [
    "section3",
    "twoSideBox",
    "subHeading2",
    "peraContent",
    "unorderList",
    "listIteam",
    "listIteam3",
    "listIteam4",
    "listIteam5",
    "listIteam6",
    "listIteam7",
    "listIteam8",
    "bannerImage2",
    "imageMarketing2"
  ],
  twoSideBox: [
    "twoSideBox",
    "subHeading2",
    "peraContent",
    "unorderList",
    "listIteam",
    "listIteam3",
    "listIteam4",
    "listIteam5",
    "listIteam6",
    "listIteam7",
    "listIteam8",
    "bannerImage2",
    "imageMarketing2"
  ],
  subHeading2: [
    "subHeading2",
    "peraContent",
    "unorderList",
    "listIteam",
    "listIteam3",
    "listIteam4",
    "listIteam5",
    "listIteam6",
    "listIteam7",
    "listIteam8"
  ],
  peraContent: ["peraContent"],
  unorderList: [
    "unorderList",
    "listIteam",
    "listIteam3",
    "listIteam4",
    "listIteam5",
    "listIteam6",
    "listIteam7",
    "listIteam8"
  ],
  listIteam: ["listIteam"],
  listIteam3: ["listIteam3"],
  listIteam4: ["listIteam4"],
  listIteam5: ["listIteam5"],
  listIteam6: ["listIteam6"],
  listIteam7: ["listIteam7"],
  listIteam8: ["listIteam8"],
  bannerImage2: ["bannerImage2", "imageMarketing2"],
  imageMarketing2: ["imageMarketing2"],
  section4: ["section4", "testimonialText", "position"],
  testimonialText: ["testimonialText"],
  position: ["position"],
  section5: ["section5", "twoSidedContent", "subHeading3", "line2"],
  twoSidedContent: ["twoSidedContent", "subHeading3", "line2"],
  subHeading3: ["subHeading3"],
  line2: ["line2"],
  section6: [
    "section6",
    "twoSideBox2",
    "subHeading4",
    "peraContent2",
    "unorderList2",
    "listIteam2",
    "listIteam9",
    "listIteam10",
    "listIteam11",
    "listIteam12",
    "listIteam13",
    "bannerImage3",
    "imageMarketing3"
  ],
  twoSideBox2: [
    "twoSideBox2",
    "subHeading4",
    "peraContent2",
    "unorderList2",
    "listIteam2",
    "listIteam9",
    "listIteam10",
    "listIteam11",
    "listIteam12",
    "listIteam13",
    "bannerImage3",
    "imageMarketing3"
  ],
  subHeading4: [
    "subHeading4",
    "peraContent2",
    "unorderList2",
    "listIteam2",
    "listIteam9",
    "listIteam10",
    "listIteam11",
    "listIteam12",
    "listIteam13"
  ],
  peraContent2: ["peraContent2"],
  unorderList2: [
    "unorderList2",
    "listIteam2",
    "listIteam9",
    "listIteam10",
    "listIteam11",
    "listIteam12",
    "listIteam13"
  ],
  listIteam2: ["listIteam2"],
  listIteam9: ["listIteam9"],
  listIteam10: ["listIteam10"],
  listIteam11: ["listIteam11"],
  listIteam12: ["listIteam12"],
  listIteam13: ["listIteam13"],
  bannerImage3: ["bannerImage3", "imageMarketing3"],
  imageMarketing3: ["imageMarketing3"],
  section7: [
    "section7",
    "subHeading5",
    "line3",
    "blockChapterContent",
    "blockChapterContent4",
    "blockChapterContent2",
    "blockChapterContent3"
  ],
  subHeading5: ["subHeading5"],
  line3: ["line3"],
  blockChapterContent: ["blockChapterContent"],
  blockChapterContent4: ["blockChapterContent4"],
  blockChapterContent2: ["blockChapterContent2"],
  blockChapterContent3: ["blockChapterContent3"],
  section8: ["section8", "avtarContent", "avatarImage"],
  avtarContent: ["avtarContent"],
  avatarImage: ["avatarImage"],
  section9: ["section9", "svg"],
  svg: ["svg"],
  footer: [
    "footer",
    "footerLogo",
    "logo2",
    "footerLink",
    "footerLink2",
    "footerLink4",
    "footerLink5"
  ],
  footerLogo: ["footerLogo", "logo2"],
  logo2: ["logo2"],
  footerLink: ["footerLink"],
  footerLink2: ["footerLink2"],
  footerLink4: ["footerLink4"],
  footerLink5: ["footerLink5"],
  copyRight: ["copyRight"],
  socialIcons: ["socialIcons", "twitter", "facebook", "youtube", "vimeo"],
  twitter: ["twitter"],
  facebook: ["facebook"],
  youtube: ["youtube"],
  vimeo: ["vimeo"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  navBar: "header";
  logoWrap: "div";
  logo: typeof PlasmicImg__;
  navmenu: "div";
  link3: "a";
  link2: "a";
  navBarButtonBlock: "div";
  button: typeof Button;
  btnText: "div";
  section1: "section";
  container: "div";
  flexBox: "div";
  bannerImage: "div";
  contentBlock: "div";
  mainHeading: "h1";
  peraBanner: "p";
  section2: "section";
  subHeading: "h2";
  logoContainer: "div";
  section3: "section";
  twoSideBox: "div";
  subHeading2: "h2";
  peraContent: "p";
  unorderList: "ul";
  listIteam: "li";
  listIteam3: "li";
  listIteam4: "li";
  listIteam5: "li";
  listIteam6: "li";
  listIteam7: "li";
  listIteam8: "li";
  bannerImage2: "div";
  imageMarketing2: typeof PlasmicImg__;
  section4: "section";
  testimonialText: "h2";
  position: "p";
  section5: "section";
  twoSidedContent: "div";
  subHeading3: "h2";
  line2: "div";
  section6: "section";
  twoSideBox2: "div";
  subHeading4: "h2";
  peraContent2: "p";
  unorderList2: "ul";
  listIteam2: "li";
  listIteam9: "li";
  listIteam10: "li";
  listIteam11: "li";
  listIteam12: "li";
  listIteam13: "li";
  bannerImage3: "div";
  imageMarketing3: typeof PlasmicImg__;
  section7: "section";
  subHeading5: "h2";
  line3: "div";
  blockChapterContent: "div";
  blockChapterContent4: "div";
  blockChapterContent2: "div";
  blockChapterContent3: "div";
  section8: "section";
  avtarContent: "div";
  avatarImage: "div";
  section9: "section";
  svg: "svg";
  footer: "footer";
  footerLogo: "div";
  logo2: typeof PlasmicImg__;
  footerLink: "a";
  footerLink2: "a";
  footerLink4: "a";
  footerLink5: "a";
  copyRight: "p";
  socialIcons: "div";
  twitter: typeof PlasmicImg__;
  facebook: typeof PlasmicImg__;
  youtube: typeof PlasmicImg__;
  vimeo: typeof PlasmicImg__;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicHomepage__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navBar: makeNodeComponent("navBar"),
    logoWrap: makeNodeComponent("logoWrap"),
    logo: makeNodeComponent("logo"),
    navmenu: makeNodeComponent("navmenu"),
    link3: makeNodeComponent("link3"),
    link2: makeNodeComponent("link2"),
    navBarButtonBlock: makeNodeComponent("navBarButtonBlock"),
    button: makeNodeComponent("button"),
    btnText: makeNodeComponent("btnText"),
    section1: makeNodeComponent("section1"),
    container: makeNodeComponent("container"),
    flexBox: makeNodeComponent("flexBox"),
    bannerImage: makeNodeComponent("bannerImage"),
    contentBlock: makeNodeComponent("contentBlock"),
    mainHeading: makeNodeComponent("mainHeading"),
    peraBanner: makeNodeComponent("peraBanner"),
    section2: makeNodeComponent("section2"),
    subHeading: makeNodeComponent("subHeading"),
    logoContainer: makeNodeComponent("logoContainer"),
    section3: makeNodeComponent("section3"),
    twoSideBox: makeNodeComponent("twoSideBox"),
    subHeading2: makeNodeComponent("subHeading2"),
    peraContent: makeNodeComponent("peraContent"),
    unorderList: makeNodeComponent("unorderList"),
    listIteam: makeNodeComponent("listIteam"),
    listIteam3: makeNodeComponent("listIteam3"),
    listIteam4: makeNodeComponent("listIteam4"),
    listIteam5: makeNodeComponent("listIteam5"),
    listIteam6: makeNodeComponent("listIteam6"),
    listIteam7: makeNodeComponent("listIteam7"),
    listIteam8: makeNodeComponent("listIteam8"),
    bannerImage2: makeNodeComponent("bannerImage2"),
    imageMarketing2: makeNodeComponent("imageMarketing2"),
    section4: makeNodeComponent("section4"),
    testimonialText: makeNodeComponent("testimonialText"),
    position: makeNodeComponent("position"),
    section5: makeNodeComponent("section5"),
    twoSidedContent: makeNodeComponent("twoSidedContent"),
    subHeading3: makeNodeComponent("subHeading3"),
    line2: makeNodeComponent("line2"),
    section6: makeNodeComponent("section6"),
    twoSideBox2: makeNodeComponent("twoSideBox2"),
    subHeading4: makeNodeComponent("subHeading4"),
    peraContent2: makeNodeComponent("peraContent2"),
    unorderList2: makeNodeComponent("unorderList2"),
    listIteam2: makeNodeComponent("listIteam2"),
    listIteam9: makeNodeComponent("listIteam9"),
    listIteam10: makeNodeComponent("listIteam10"),
    listIteam11: makeNodeComponent("listIteam11"),
    listIteam12: makeNodeComponent("listIteam12"),
    listIteam13: makeNodeComponent("listIteam13"),
    bannerImage3: makeNodeComponent("bannerImage3"),
    imageMarketing3: makeNodeComponent("imageMarketing3"),
    section7: makeNodeComponent("section7"),
    subHeading5: makeNodeComponent("subHeading5"),
    line3: makeNodeComponent("line3"),
    blockChapterContent: makeNodeComponent("blockChapterContent"),
    blockChapterContent4: makeNodeComponent("blockChapterContent4"),
    blockChapterContent2: makeNodeComponent("blockChapterContent2"),
    blockChapterContent3: makeNodeComponent("blockChapterContent3"),
    section8: makeNodeComponent("section8"),
    avtarContent: makeNodeComponent("avtarContent"),
    avatarImage: makeNodeComponent("avatarImage"),
    section9: makeNodeComponent("section9"),
    svg: makeNodeComponent("svg"),
    footer: makeNodeComponent("footer"),
    footerLogo: makeNodeComponent("footerLogo"),
    logo2: makeNodeComponent("logo2"),
    footerLink: makeNodeComponent("footerLink"),
    footerLink2: makeNodeComponent("footerLink2"),
    footerLink4: makeNodeComponent("footerLink4"),
    footerLink5: makeNodeComponent("footerLink5"),
    copyRight: makeNodeComponent("copyRight"),
    socialIcons: makeNodeComponent("socialIcons"),
    twitter: makeNodeComponent("twitter"),
    facebook: makeNodeComponent("facebook"),
    youtube: makeNodeComponent("youtube"),
    vimeo: makeNodeComponent("vimeo"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
